# estágio de compilação
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY . .
RUN rm -rf dist
RUN rm -rf node_modules
# COPY package*.json ./
RUN npm install
RUN npm run build

EXPOSE 80
CMD ["npm", "start"]